-- MySQL Script generated by MySQL Workbench
-- Sat Feb 26 17:03:49 2022
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema gestion-formation
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema gestion-formation
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `gestion-formation` DEFAULT CHARACTER SET utf8 ;
USE `gestion-formation` ;

-- -----------------------------------------------------
-- Table `gestion-formation`.`gf_domain`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `gestion-formation`.`gf_domain` (
  `id_domain` INT NOT NULL AUTO_INCREMENT,
  `denominate` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id_domain`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `gestion-formation`.`gf_course`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `gestion-formation`.`gf_course` (
  `id_course` INT NOT NULL AUTO_INCREMENT,
  `gf_domain_id_domain` INT NOT NULL,
  PRIMARY KEY (`id_course`),
  INDEX `fk_gf_course_gf_domain1_idx` (`gf_domain_id_domain` ASC) VISIBLE,
  CONSTRAINT `fk_gf_course_gf_domain1`
    FOREIGN KEY (`gf_domain_id_domain`)
    REFERENCES `gestion-formation`.`gf_domain` (`id_domain`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `gestion-formation`.`gf_survey`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `gestion-formation`.`gf_survey` (
  `id_survey` INT NOT NULL AUTO_INCREMENT,
  `type` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id_survey`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `gestion-formation`.`gf_user`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `gestion-formation`.`gf_user` (
  `id_user` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NOT NULL,
  `password` TEXT NOT NULL,
  `email` VARCHAR(45) NOT NULL,
  `role` VARCHAR(45) NOT NULL,
  `gf_course_id_course` INT NULL,
  `gf_survey_id_survey` INT NULL,
  `gf_course_id_course1` INT NULL,
  PRIMARY KEY (`id_user`),
  INDEX `fk_gf_user_gf_course1_idx` (`gf_course_id_course` ASC) VISIBLE,
  INDEX `fk_gf_user_gf_survey1_idx` (`gf_survey_id_survey` ASC) VISIBLE,
  INDEX `fk_gf_user_gf_course2_idx` (`gf_course_id_course1` ASC) VISIBLE,
  CONSTRAINT `fk_gf_user_gf_course1`
    FOREIGN KEY (`gf_course_id_course`)
    REFERENCES `gestion-formation`.`gf_course` (`id_course`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_gf_user_gf_survey1`
    FOREIGN KEY (`gf_survey_id_survey`)
    REFERENCES `gestion-formation`.`gf_survey` (`id_survey`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_gf_user_gf_course2`
    FOREIGN KEY (`gf_course_id_course1`)
    REFERENCES `gestion-formation`.`gf_course` (`id_course`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `gestion-formation`.`gf_graph`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `gestion-formation`.`gf_graph` (
  `id_graph` INT NOT NULL AUTO_INCREMENT,
  PRIMARY KEY (`id_graph`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `gestion-formation`.`gf_training`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `gestion-formation`.`gf_training` (
  `id_training` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NULL,
  PRIMARY KEY (`id_training`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `gestion-formation`.`course_has_training`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `gestion-formation`.`course_has_training` (
  `gf_training_id_training` INT NOT NULL,
  `gf_course_id_course` INT NOT NULL,
  PRIMARY KEY (`gf_training_id_training`, `gf_course_id_course`),
  INDEX `fk_gf_training_has_gf_course_gf_course1_idx` (`gf_course_id_course` ASC) VISIBLE,
  INDEX `fk_gf_training_has_gf_course_gf_training_idx` (`gf_training_id_training` ASC) VISIBLE,
  CONSTRAINT `fk_gf_training_has_gf_course_gf_training`
    FOREIGN KEY (`gf_training_id_training`)
    REFERENCES `gestion-formation`.`gf_training` (`id_training`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_gf_training_has_gf_course_gf_course1`
    FOREIGN KEY (`gf_course_id_course`)
    REFERENCES `gestion-formation`.`gf_course` (`id_course`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `gestion-formation`.`learner_has_graph`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `gestion-formation`.`learner_has_graph` (
  `gf_user_id_user` INT NOT NULL,
  `gf_graph_id_graph` INT NOT NULL,
  PRIMARY KEY (`gf_user_id_user`, `gf_graph_id_graph`),
  INDEX `fk_gf_user_has_gf_graph_gf_graph1_idx` (`gf_graph_id_graph` ASC) VISIBLE,
  INDEX `fk_gf_user_has_gf_graph_gf_user1_idx` (`gf_user_id_user` ASC) VISIBLE,
  CONSTRAINT `fk_gf_user_has_gf_graph_gf_user1`
    FOREIGN KEY (`gf_user_id_user`)
    REFERENCES `gestion-formation`.`gf_user` (`id_user`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_gf_user_has_gf_graph_gf_graph1`
    FOREIGN KEY (`gf_graph_id_graph`)
    REFERENCES `gestion-formation`.`gf_graph` (`id_graph`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `gestion-formation`.`gf_graph_has_gf_graph`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `gestion-formation`.`gf_graph_has_gf_graph` (
  `gf_graph_id_graph` INT NOT NULL,
  `gf_graph_id_graph1` INT NOT NULL,
  PRIMARY KEY (`gf_graph_id_graph`, `gf_graph_id_graph1`),
  INDEX `fk_gf_graph_has_gf_graph_gf_graph2_idx` (`gf_graph_id_graph1` ASC) VISIBLE,
  INDEX `fk_gf_graph_has_gf_graph_gf_graph1_idx` (`gf_graph_id_graph` ASC) VISIBLE,
  CONSTRAINT `fk_gf_graph_has_gf_graph_gf_graph1`
    FOREIGN KEY (`gf_graph_id_graph`)
    REFERENCES `gestion-formation`.`gf_graph` (`id_graph`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_gf_graph_has_gf_graph_gf_graph2`
    FOREIGN KEY (`gf_graph_id_graph1`)
    REFERENCES `gestion-formation`.`gf_graph` (`id_graph`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `gestion-formation`.`trainer_edit_graph`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `gestion-formation`.`trainer_edit_graph` (
  `gf_graph_id_graph` INT NOT NULL,
  `gf_user_id_user` INT NOT NULL,
  PRIMARY KEY (`gf_graph_id_graph`, `gf_user_id_user`),
  INDEX `fk_gf_graph_has_gf_user_gf_user1_idx` (`gf_user_id_user` ASC) VISIBLE,
  INDEX `fk_gf_graph_has_gf_user_gf_graph1_idx` (`gf_graph_id_graph` ASC) VISIBLE,
  CONSTRAINT `fk_gf_graph_has_gf_user_gf_graph1`
    FOREIGN KEY (`gf_graph_id_graph`)
    REFERENCES `gestion-formation`.`gf_graph` (`id_graph`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_gf_graph_has_gf_user_gf_user1`
    FOREIGN KEY (`gf_user_id_user`)
    REFERENCES `gestion-formation`.`gf_user` (`id_user`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `gestion-formation`.`gf_skill`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `gestion-formation`.`gf_skill` (
  `id_skill` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NOT NULL,
  `weight` VARCHAR(45) NOT NULL,
  `gf_user_id_user` INT NOT NULL,
  PRIMARY KEY (`id_skill`),
  INDEX `fk_gf_skill_gf_user1_idx` (`gf_user_id_user` ASC) VISIBLE,
  CONSTRAINT `fk_gf_skill_gf_user1`
    FOREIGN KEY (`gf_user_id_user`)
    REFERENCES `gestion-formation`.`gf_user` (`id_user`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `gestion-formation`.`graph_has_skill`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `gestion-formation`.`graph_has_skill` (
  `gf_graph_id_graph` INT NOT NULL,
  `gf_skill_id_skill` INT NOT NULL,
  PRIMARY KEY (`gf_graph_id_graph`, `gf_skill_id_skill`),
  INDEX `fk_gf_graph_has_gf_skill_gf_skill1_idx` (`gf_skill_id_skill` ASC) VISIBLE,
  INDEX `fk_gf_graph_has_gf_skill_gf_graph1_idx` (`gf_graph_id_graph` ASC) VISIBLE,
  CONSTRAINT `fk_gf_graph_has_gf_skill_gf_graph1`
    FOREIGN KEY (`gf_graph_id_graph`)
    REFERENCES `gestion-formation`.`gf_graph` (`id_graph`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_gf_graph_has_gf_skill_gf_skill1`
    FOREIGN KEY (`gf_skill_id_skill`)
    REFERENCES `gestion-formation`.`gf_skill` (`id_skill`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `gestion-formation`.`composing_skill`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `gestion-formation`.`composing_skill` (
  `gf_skill_id_skill` INT NOT NULL,
  `gf_skill_id_skill1` INT NOT NULL,
  PRIMARY KEY (`gf_skill_id_skill`, `gf_skill_id_skill1`),
  INDEX `fk_gf_skill_has_gf_skill_gf_skill2_idx` (`gf_skill_id_skill1` ASC) VISIBLE,
  INDEX `fk_gf_skill_has_gf_skill_gf_skill1_idx` (`gf_skill_id_skill` ASC) VISIBLE,
  CONSTRAINT `fk_gf_skill_has_gf_skill_gf_skill1`
    FOREIGN KEY (`gf_skill_id_skill`)
    REFERENCES `gestion-formation`.`gf_skill` (`id_skill`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_gf_skill_has_gf_skill_gf_skill2`
    FOREIGN KEY (`gf_skill_id_skill1`)
    REFERENCES `gestion-formation`.`gf_skill` (`id_skill`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `gestion-formation`.`gf_question`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `gestion-formation`.`gf_question` (
  `id_question` INT NOT NULL AUTO_INCREMENT,
  `level` VARCHAR(45) NOT NULL,
  `difficulty` VARCHAR(45) NOT NULL,
  `contents` TEXT NOT NULL,
  `gf_domain_id_domain` INT NOT NULL,
  `gf_skill_id_skill` INT NOT NULL,
  PRIMARY KEY (`id_question`),
  INDEX `fk_gf_question_gf_domain1_idx` (`gf_domain_id_domain` ASC) VISIBLE,
  INDEX `fk_gf_question_gf_skill1_idx` (`gf_skill_id_skill` ASC) VISIBLE,
  CONSTRAINT `fk_gf_question_gf_domain1`
    FOREIGN KEY (`gf_domain_id_domain`)
    REFERENCES `gestion-formation`.`gf_domain` (`id_domain`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_gf_question_gf_skill1`
    FOREIGN KEY (`gf_skill_id_skill`)
    REFERENCES `gestion-formation`.`gf_skill` (`id_skill`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `gestion-formation`.`gf_proposal`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `gestion-formation`.`gf_proposal` (
  `id_proposal` INT NOT NULL AUTO_INCREMENT,
  `denominate` VARCHAR(50) NOT NULL,
  `state` TINYINT NOT NULL,
  `gf_question_id_question` INT NOT NULL,
  PRIMARY KEY (`id_proposal`),
  INDEX `fk_gf_proposal_gf_question1_idx` (`gf_question_id_question` ASC) VISIBLE,
  CONSTRAINT `fk_gf_proposal_gf_question1`
    FOREIGN KEY (`gf_question_id_question`)
    REFERENCES `gestion-formation`.`gf_question` (`id_question`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `gestion-formation`.`survey_has_question`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `gestion-formation`.`survey_has_question` (
  `gf_survey_id_survey` INT NOT NULL,
  `gf_question_id_question` INT NOT NULL,
  PRIMARY KEY (`gf_survey_id_survey`, `gf_question_id_question`),
  INDEX `fk_gf_survey_has_gf_question_gf_question1_idx` (`gf_question_id_question` ASC) VISIBLE,
  INDEX `fk_gf_survey_has_gf_question_gf_survey1_idx` (`gf_survey_id_survey` ASC) VISIBLE,
  CONSTRAINT `fk_gf_survey_has_gf_question_gf_survey1`
    FOREIGN KEY (`gf_survey_id_survey`)
    REFERENCES `gestion-formation`.`gf_survey` (`id_survey`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_gf_survey_has_gf_question_gf_question1`
    FOREIGN KEY (`gf_question_id_question`)
    REFERENCES `gestion-formation`.`gf_question` (`id_question`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `gestion-formation`.`former_manage_question`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `gestion-formation`.`former_manage_question` (
  `gf_user_id_user` INT NOT NULL,
  `gf_question_id_question` INT NOT NULL,
  PRIMARY KEY (`gf_user_id_user`, `gf_question_id_question`),
  INDEX `fk_gf_user_has_gf_question_gf_question1_idx` (`gf_question_id_question` ASC) VISIBLE,
  INDEX `fk_gf_user_has_gf_question_gf_user1_idx` (`gf_user_id_user` ASC) VISIBLE,
  CONSTRAINT `fk_gf_user_has_gf_question_gf_user1`
    FOREIGN KEY (`gf_user_id_user`)
    REFERENCES `gestion-formation`.`gf_user` (`id_user`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_gf_user_has_gf_question_gf_question1`
    FOREIGN KEY (`gf_question_id_question`)
    REFERENCES `gestion-formation`.`gf_question` (`id_question`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
